[tools]
node = "20"
pnpm = "latest"
"npm:repomix" = "latest"
"npm:vercel" = "latest"

[hooks]

[env]
_.path = ['./node_modules/.bin']

[tasks.pnpm-install]
description = 'Installs dependencies with pnpm'
run = 'pnpm install'
sources = ['package.json', 'pnpm-lock.yaml', 'mise.toml']
outputs = ['node_modules/.pnpm/lock.yaml']

[tasks.dev]
description = 'Calls your dev script in `package.json`'
run = 'npm run dev'
depends = ['pnpm-install']

[tasks.clean]
description = 'Clears out dist'
run = 'rm -rf dist/'

[tasks.build]
description = 'Clears out dist'
run = ['npm run build', 'du -sh dist']
depends = ['pnpm-install','clean']

[tasks.db-seed]
description = 'Resets the local database'
run = ['supabase db reset --local --no-seed']

[tasks.sync-products]
description = 'Syncs products from stripe'
run = ['dotenvx run -- tsx scripts/sync_stripe_products.ts']

[tasks.llm-dump]
description = 'Runs repomix'
run = ['repomix --ignore "output*,**/*.log,tmp/,inputs/**/*md,data_integrity/**/*.json"']
